language: python

python:
    - '3.7-dev'

env:
    - DIST=dist

install:
    - sudo apt-get install debhelper devscripts
    - pip install -r requirements.build.txt
    - pip install -r requirements.lint.txt
    - pip install -r requirements.install.txt
    - python setup.py bdist_wheel --dist-dir=${DIST}
    - pip install --upgrade --ignore-installed --no-deps --find-links=${DIST}
    - debuild --no-tgz-check -us -uc

script:
    - flake8

deploy:
    provider: releases
    api_key:
        secure: HmulyEDMr4bpEjIxU8FXGU3UZpMc2m+o45hw3r6mkt03ON/V/b8bECs0KPCcOvCvFBDB/KXY3iG6SDIqn6uIOTheqMDGTiOmdZfTQlgXgomW6+cZX3ukKfEOD47MXsceD6gwW83Cw+6uOaPr9HZccb7UjSlp11vaN4rucE57uE4crex/jwwePkvAeAggG9N0Bh+A1lQRhBRAHuBjMC/1OTlaoWt0k2aZly6V7bM7iBXyQyf51GcO949XNSNLUndgJzO8CQjpFxGcjbITuMu8bG1t0MDxVFUh8jc+s54k29EITDfhsliqe5In0qe0s7BesBbY5wDZLaN+SbEWzxqGk5I3evPM2h1oaZgOo44oF5eMrVwf9PxwL3q5tqUCUUgkysdN/AJEWEGAh9SiQapiJybOXxTzPo8MNFc5pnG5C5AVyEhk9ulRbXep6+8mLfH9cZMOiWCbIDJb/OruRMfODtoBLaSNYvRLo/FPcAVBg3U90acVaPtAbph8YEfTdGfimdE3DHWqRCHY8xPqNoUar42UUtzhha7bFOOgx+UviJFkuKGX23ltUrXd7tW3GDEJck2saSTGcSwaet8hNqpAxMBVpeL1MDXPZOKr/j8xFLtoxuU2cZf6l8S4ENApRDr9ZSiLwp3PwPEGSNniL0eMGmpk9PjVSOLI31QtuWrvfpM=
    skip_cleanup: true
    file_glob: true
    file:
        - "${DIST}/*.whl"
        - "../*.deb"
    on:
        repo: subsinthe/blabbermouth
        branch: master
        tags: true
