language: python

python:
    - '3.7-dev'

env:
    - DIST=pip-wheel-metadata

install:
    - sudo apt-get install debhelper devscripts
    - pip install poetry
    - poetry build
    - poetry install

script:
    - debuild --no-tgz-check -us -uc

deploy:
    provider: releases
    api_key:
        secure: F1I3//X6OYtPv6Aoe9hskvRxmK1yK2lnymFaIAJ6HAYuO/3Uilx+goYQBMCHwYJUiRlONLYr6PnNyl6aqvroKFk5hoHBbrQ/YT8IxQziPElpkWjOUwM8ZNtUyae14xpY9tdg3sdr91JXaQ7967dffix6hidonwEs6OFimep3IqYjFwhiFj5PupIwyg6Sw5Ihvl/yT5fAh7tXfBiGGpBKo2+2Zs4B5sdlI34rycTj8f66gr3vrvyzOo4FHiG/EwzftYiV4d4Jv+fNPdE3dG7FJkGbfCcnn3IO1JSpmGzxZ2f1RJpKUnOA4ZlsuRt8eeKF6C8aHYnm4dFdbbL5LErJwzn9MMnn1hWH5myGe04Y0sF98lOCyAsizQZXj3JoJq7aKfc+fbVAINGu++ZJshqbjdIySMSjmEdhRc7eBFznUm5DIJVH1ZkgSQ8KxLK7MTR51FL8XQlu788GU/1C093vWpt7GM062s5WGKBq//Sc1hhPwpLk8hUW/VuM8jcUXjplLRTkL1QEqC9UXl6dwQkiIkLsIyswtBmmtDPgxYSNC7xubwXVfxByJwfaj8ZgN7BCLtdK9V8hcyLE8Qo8DdWiVteYEYR46Ki1B4z+xX8BS3nHiDqCaLF/024GqnCw9lpDX6eypmfgqC5OJBoCSHe3Zhbwk4XyX9Gnc64qU8HVSA4=
    skip_cleanup: true
    file_glob: true
    file:
        - "${DIST}/*.whl"
        - "../*.deb"
    on:
        repo: subsinthe/blabbermouth
        branch: master
